theme: jekyll-theme-minimal

title: Haorui He (何昊睿)
description: AI Practitioner, Software Developer, and Football Fan. Order may vary according to circumstances.<br>
logo: /assets/pic.jpg
show_downloads: true
